PROJECT = hep_udp_listener

DEPS = cowboy hep

dep_cowboy = pkg://cowboy master
dep_hep = pkg://hep master

PKG_FILE_URL = https://raw.github.com/pannonia-incubator/packages-erlang/master/packages.v1.tsv

include ../../erlang.mk
